---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: javawebapp
  name: java-controller
spec:
  replicas: {{.Values.replicas}}
  template:
    metadata:
      labels:
        name: javawebapp
    spec:
      containers:
      - image: nginx
        name: javawebapp
        ports:
        - name: javawebapp
          containerPort: 80
